import type { XrayAnswer, XrayCategory } from "./types";

export const xrayLabels: Record<XrayCategory, string> = { entrada: "Entrada dos Leads", mensagem: "Mensagem e Filtro", qualificacao: "Qualificação Comercial", comercial: "Reunião e Comercial" };
type Option = { text: string; score: number };
export type XrayQuestion = { id: number; category: XrayCategory; title: string; subtitle: string; options: Option[] };
const o = (...texts: string[]): Option[] => texts.map((text, score) => ({ text, score }));
export const xrayQuestions: XrayQuestion[] = [
  { id: 1, category: "entrada", title: "Hoje, como a maioria dos leads chega até você?", subtitle: "Pense no caminho mais comum antes da pessoa chamar você ou seu time.", options: o("Chegam por canais diferentes e eu não sei bem de onde vieram.", "Chegam principalmente por Instagram, indicação ou WhatsApp, mas sem muita organização.", "Chegam por canais definidos, mas ainda sem filtro antes da conversa.", "Chegam por canais definidos e já passam por algum tipo de qualificação.") },
  { id: 2, category: "entrada", title: "Quando o lead chama você ou sua equipe, ele já chega com contexto?", subtitle: "Ele entende minimamente o que você faz e por que deveria conversar?", options: o("Não. Geralmente chega perdido ou perguntando preço.", "Chega com uma ideia vaga, mas ainda precisa entender quase tudo.", "Chega sabendo parte do que oferecemos.", "Chega entendendo a oferta, a dor e o próximo passo.") },
  { id: 3, category: "entrada", title: "Qual comportamento mais aparece nos seus leads?", subtitle: "Escolha o padrão mais frequente hoje.", options: o("Pedem preço e somem.", "Dizem que têm interesse, mas param de responder.", "Alguns avançam, mas muitos ainda chegam sem perfil.", "A maioria que avança tem intenção real.") },
  { id: 4, category: "mensagem", title: "Antes do WhatsApp ou da conversa, existe algum filtro?", subtitle: "Existe alguma barreira antes da pessoa ocupar seu atendimento?", options: o("Não. Qualquer pessoa pode chamar direto.", "Existe uma chamada ou botão, mas sem qualificação.", "Existe formulário, pergunta ou etapa simples antes do contato.", "Existe uma triagem clara antes da conversa comercial.") },
  { id: 5, category: "mensagem", title: "Sua comunicação deixa claro para quem sua oferta é?", subtitle: "A pessoa certa se identifica rapidamente com a mensagem?", options: o("Não. A mensagem é genérica.", "Mais ou menos. Falo da solução, mas não filtro perfil.", "Sim, mas ainda poderia ser mais específica.", "Sim. A pessoa certa se identifica e a errada tende a sair.") },
  { id: 6, category: "mensagem", title: "Sua comunicação afasta quem não tem perfil?", subtitle: "Um bom funil também repele quem não deveria avançar.", options: o("Não. Tento atrair todo mundo.", "Não diretamente, tenho medo de perder leads.", "Às vezes uso algum aviso ou critério.", "Sim. Deixo claro quem não deve avançar.") },
  { id: 7, category: "qualificacao", title: "Você faz perguntas antes de apresentar a solução?", subtitle: "Ou explica a oferta antes de entender o cenário do lead?", options: o("Não. Já explico a oferta ou mando preço.", "Faço algumas perguntas, mas sem padrão.", "Tenho algumas perguntas importantes.", "Tenho perguntas claras antes de oferecer solução.") },
  { id: 8, category: "qualificacao", title: "Você avalia dor, urgência e capacidade antes de avançar o lead?", subtitle: "Esses são sinais básicos de uma oportunidade real.", options: o("Não avalio. Se chamou, eu atendo.", "Avalio de forma subjetiva durante a conversa.", "Avalio alguns desses pontos, mas sem critério fixo.", "Avalio dor, urgência, perfil e capacidade antes de avançar.") },
  { id: 9, category: "qualificacao", title: "Você classifica seus leads?", subtitle: "Existe diferença prática entre lead quente, morno e frio?", options: o("Não. Todo lead é tratado igual.", "Classifico mentalmente, mas sem registro.", "Classifico como bom ou ruim, mas sem muita clareza.", "Classifico como quente, morno ou frio com critérios claros.") },
  { id: 10, category: "comercial", title: "Existe critério para agendar reunião?", subtitle: "A reunião é marcada por intenção real ou apenas interesse?", options: o("Não. Se a pessoa quer, agenda.", "Agendo quando parece interessada.", "Tenho alguns critérios antes de agendar.", "Só agenda quem tem fit, intenção e próximo passo claro.") },
  { id: 11, category: "comercial", title: "Quem faz a venda recebe contexto antes da conversa?", subtitle: "O responsável pela call sabe com quem está falando?", options: o("Não. Vai praticamente às cegas.", "Recebe só nome e contato.", "Recebe algumas informações importantes.", "Recebe contexto sobre dor, urgência, perfil e objeções.") },
  { id: 12, category: "comercial", title: "O lead ruim está consumindo tempo, verba ou energia do seu time?", subtitle: "Pense no impacto real de atender pessoas que não vão comprar.", options: o("Muito. Isso atrapalha o comercial e o caixa.", "Bastante. Ainda gastamos tempo com curiosos.", "Um pouco. Já filtramos alguns, mas ainda vaza.", "Pouco. O time foca mais em oportunidades reais.") },
];

export const bottlenecks = {
  entrada: { title: "Seu maior vazamento está na entrada dos leads", text: "Os leads chegam sem consciência, contexto e clareza. O comercial tenta educar pessoas que talvez nunca devessem avançar.", action: "Ajustar promessa, CTA e canal de entrada." },
  mensagem: { title: "Seu maior vazamento está na mensagem e no filtro", text: "Sua comunicação chama atenção, mas ainda não separa perfil de curiosidade.", action: "Criar mensagem-filtro com dor específica e frase anti-curioso." },
  qualificacao: { title: "Seu maior vazamento está na qualificação", text: "A conversa não identifica intenção real cedo o suficiente.", action: "Criar cinco perguntas obrigatórias antes de apresentar a solução." },
  comercial: { title: "Seu maior vazamento está na passagem para a venda", text: "Reuniões acontecem sem contexto suficiente ou com pessoas que ainda não deveriam estar ali.", action: "Criar critérios de agendamento e contexto mínimo." },
};

export function getXrayResult(score: number) {
  if (score <= 7) return { name: "Funil Cego", level: "Crítico", diagnosis: "Seu funil está atraindo pessoas sem saber quem realmente tem intenção de compra. Hoje, o maior problema não parece ser falta de lead. O problema é que qualquer pessoa pode entrar, perguntar, consumir tempo e avançar como se fosse oportunidade.", symptoms: ["O lead chega sem contexto.", "A comunicação é genérica.", "O WhatsApp vira suporte de curioso.", "Você não sabe qual canal traz comprador.", "O comercial só descobre tarde demais que o lead não tem perfil."], cost: "Tempo, verba, energia comercial e previsibilidade de caixa.", nextStep: "Antes de pensar em mais tráfego, crie a primeira barreira: uma mensagem e uma triagem simples para separar curioso de comprador.", impact: "Você não tem um problema de volume. Você tem um problema de entrada." };
  if (score <= 14) return { name: "Funil Solto", level: "Alto", diagnosis: "Seu funil já capta leads, mas ainda não qualifica com critério. Existe movimento, mas falta controle. As pessoas chegam, chamam, perguntam, somem e obrigam você ou seu time a descobrir manualmente quem vale atenção.", symptoms: ["Você até gera leads, mas muitos não têm intenção real.", "O WhatsApp recebe contatos sem filtro.", "A conversa depende muito do feeling do atendente.", "O time perde tempo tentando separar quem compra de quem só está olhando.", "A agenda pode estar cheia, mas nem sempre produtiva."], cost: "Tempo comercial, follow-ups improdutivos e reuniões com baixa chance de fechamento.", nextStep: "Criar critérios mínimos antes da conversa: dor, urgência, perfil e capacidade.", impact: "Seu funil não está parado. Ele está solto." };
  if (score <= 22) return { name: "Funil Reativo", level: "Médio", diagnosis: "Seu funil responde, mas ainda não conduz. Você já tem algum processo, mas o lead ainda controla boa parte da conversa. Quando ele pergunta preço, você responde. Quando ele some, você corre atrás. Quando ele agenda, nem sempre chega com contexto suficiente.", symptoms: ["O processo existe, mas não é seguido sempre.", "O lead ainda dita o ritmo da conversa.", "A qualificação acontece tarde.", "O comercial recebe oportunidades com pouco contexto.", "Você resolve casos, mas não controla a entrada."], cost: "Energia operacional, velocidade comercial e oportunidades perdidas por falta de direção.", nextStep: "Definir uma sequência fixa de triagem antes de apresentar preço, proposta ou agenda.", impact: "Você não precisa responder mais rápido. Precisa conduzir melhor." };
  if (score <= 29) return { name: "Funil Parcial", level: "Moderado", diagnosis: "Seu funil já possui filtros e critérios importantes, mas ainda existem pontos de escape. Parte dos leads chega preparada e parte ainda avança sem o nível de intenção ou contexto ideal.", symptoms: ["Alguns canais trazem leads melhores que outros.", "A comunicação filtra, mas não em todas as etapas.", "A qualificação funciona dependendo de quem atende.", "Ainda existem reuniões que poderiam ter sido evitadas.", "O processo precisa de mais consistência."], cost: "Pequenos vazamentos que somados reduzem a produtividade e previsibilidade do comercial.", nextStep: "Padronizar os critérios que já funcionam e aplicá-los em todos os canais e atendimentos.", impact: "Seu funil já tem estrutura. Agora precisa de consistência." };
  return { name: "Funil com Filtro Inicial", level: "Controlado", diagnosis: "Seu funil já protege bem o tempo do comercial. Os leads chegam com mais contexto, existe triagem e o time tende a conversar com oportunidades mais qualificadas. O próximo ganho está em refinamento e escala.", symptoms: ["Os leads entendem melhor a oferta antes de chamar.", "Existe filtro antes da conversa comercial.", "O time recebe contexto relevante.", "A agenda é mais seletiva.", "O processo já afasta parte dos curiosos."], cost: "O custo do lead ruim está mais controlado, mas ainda pode haver espaço para melhorar conversão e velocidade.", nextStep: "Refinar a mensagem, os critérios e a automação para aumentar a qualidade sem reduzir o volume de oportunidades.", impact: "Você já filtra. Agora pode transformar triagem em vantagem competitiva." };
}

export function getMainBottleneck(answers: XrayAnswer[]): XrayCategory {
  const totals: Record<XrayCategory, number> = { entrada: 0, mensagem: 0, qualificacao: 0, comercial: 0 };
  answers.forEach((answer) => { totals[answer.category] += answer.score; });
  return (["mensagem", "qualificacao", "entrada", "comercial"] as XrayCategory[]).reduce((lowest, category) => totals[category] < totals[lowest] ? category : lowest, "mensagem");
}

export function getXrayProblem(score: number, bottleneck: XrayCategory) {
  return `${getXrayResult(score).diagnosis} ${bottlenecks[bottleneck].text}`;
}

export function generateXrayText(answers: XrayAnswer[]) {
  const score = answers.reduce((total, answer) => total + answer.score, 0);
  const bottleneck = getMainBottleneck(answers);
  return `PROBLEMA IDENTIFICADO\n\n${getXrayProblem(score, bottleneck)}`;
}
