"use client";

import { CalendarPlus, Check, ExternalLink } from "lucide-react";
import { useEffect } from "react";
import { useApp } from "@/components/app-provider";
import { Button, PageHeader } from "@/components/ui";

export default function ImmersionPage() {
  const { data, update } = useApp(); const date = process.env.NEXT_PUBLIC_IMMERSION_DATE || "Data a confirmar"; const time = process.env.NEXT_PUBLIC_IMMERSION_TIME || "Horário a confirmar"; const room = process.env.NEXT_PUBLIC_IMMERSION_URL;
  useEffect(() => { if (!data.immersion.viewed) update((current) => ({ ...current, immersion: { ...current.immersion, viewed: true } })); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  function confirm() { update((current) => ({ ...current, immersion: { ...current.immersion, clicked: true, confirmed: true, confirmedAt: new Date().toISOString() } })); }
  return <><PageHeader eyebrow="Super Bônus" title="Imersão Do Clique ao Contrato em 48h" description="Transforme as peças construídas no MUV Starter em uma arquitetura comercial integrada e previsível." /><div className="grid gap-6 lg:grid-cols-[1.1fr_.7fr]"><div className="space-y-5"><section className="card p-7"><p className="eyebrow">O próximo nível</p><h2 className="font-serif text-3xl text-white">Do primeiro filtro ao sistema comercial</h2><p className="mt-4 leading-7 text-muted">Você já saiu do amadorismo do “tentar vender”. Agora o próximo nível é parar de depender de esforço e começar a operar um sistema.</p></section><section className="card"><h2 className="font-semibold text-white">Agenda da Imersão</h2><div className="mt-5 space-y-4">{["Arquitetura do funil e critérios de passagem", "Mensagem, aquisição e intenção", "Triagem, condução e próximos passos", "Plano de implementação em 48 horas"].map((item, index) => <div className="flex gap-4" key={item}><span className="text-xs font-bold text-gold">0{index + 1}</span><p className="text-sm text-muted">{item}</p></div>)}</div></section><section className="card"><h2 className="font-semibold text-white">O que levar</h2><div className="mt-4 space-y-2">{["Kit Filtro Anti-Curiosos", "Exemplos reais de leads e conversas", "Indicadores atuais do comercial", "Resultados gerados pela Central"].map((item) => <p className="flex items-center gap-3 text-sm text-muted" key={item}><Check size={15} className="text-gold" />{item}</p>)}</div></section></div><aside><section className="card sticky top-24 p-6"><p className="text-xs uppercase tracking-widest text-muted">Próxima turma</p><h2 className="mt-3 font-serif text-3xl text-white">{date}</h2><p className="mt-1 text-gold">{time}</p><div className="my-6 border-t border-white/8" />{data.immersion.confirmed ? <div className="rounded-xl border border-success/20 bg-success/8 p-4"><strong className="text-success">Vaga confirmada</strong><p className="mt-1 text-xs text-muted">Confirmação registrada em {new Date(data.immersion.confirmedAt!).toLocaleDateString("pt-BR")}.</p></div> : <Button className="w-full" onClick={confirm}>Confirmar minha vaga</Button>}<a className="button button-secondary mt-3 w-full" href={`https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent("Imersão Do Clique ao Contrato em 48h")}`} target="_blank" rel="noreferrer"><CalendarPlus size={16} />Adicionar ao calendário</a>{room && <a className="button button-ghost mt-3 w-full" href={room} target="_blank" rel="noreferrer">Abrir sala<ExternalLink size={16} /></a>}</section></aside></div></>;
}
