"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, Pencil } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useApp } from "./app-provider";
import { AutoSaveStatus, Button, ProgressBar, VideoLesson } from "./ui";
import { generateXrayText, getMainBottleneck, getXrayProblem, getXrayResult, xrayLabels, xrayQuestions } from "@/lib/xray";
import type { XrayAnswer } from "@/lib/types";

export function XrayForm() {
  const { data, update } = useApp(); const [answers, setAnswers] = useState<XrayAnswer[]>(data.xray.answers); const [step, setStep] = useState(data.xray.completed ? 13 : data.xray.currentStep); const [saving, setSaving] = useState(false); const [savedAt, setSavedAt] = useState(data.xray.updatedAt); const initialized = useRef(false);
  useEffect(() => { if (!initialized.current) { initialized.current = true; return; } setSaving(true); const timer = window.setTimeout(() => { const now = new Date().toISOString(); update((current) => ({ ...current, xray: { ...current.xray, answers, currentStep: step, updatedAt: now }, startedSteps: [...new Set([...current.startedSteps, "raio-x"])] })); setSavedAt(now); setSaving(false); }, 800); return () => clearTimeout(timer); }, [answers, step]); // eslint-disable-line react-hooks/exhaustive-deps
  const score = answers.reduce((total, answer) => total + answer.score, 0); const result = getXrayResult(score); const bottleneck = getMainBottleneck(answers); const generated = generateXrayText(answers);
  function choose(optionIndex: number) { const question = xrayQuestions[step - 1]; const option = question.options[optionIndex]; setAnswers((current) => { const next = [...current]; next[step - 1] = { questionId: question.id, category: question.category, answer: option.text, score: option.score, optionIndex }; return next; }); }
  function finish() { const now = new Date().toISOString(); update((current) => ({ ...current, xray: { answers, score, classification: result.name, leakLevel: result.level, bottleneck, generatedText: generated, completed: true, currentStep: 12, updatedAt: now }, startedSteps: [...new Set([...current.startedSteps, "raio-x"])] })); setSavedAt(now); setStep(13); }
  if (step === 0) return <section className="mx-auto max-w-3xl space-y-5"><VideoLesson title="Raio-X Anti-Curiosos: Como diagnosticar seu funil" /><div className="card p-7 md:p-10"><p className="eyebrow">Diagnóstico MUV Starter</p><h2 className="text-2xl font-bold text-white">Descubra onde seu funil está vazando</h2><p className="mt-4 leading-7 text-muted">Responda 12 perguntas para visualizar pontuação, classificação, nível de vazamento, gargalo e o principal problema do seu funil.</p><div className="mt-7"><XrayAnatomy score="— / 36" classification="—" leak="—" bottleneck="—" problem="Uma síntese objetiva do principal problema comercial aparecerá aqui." illustrative /></div><Button className="mt-7 w-full sm:w-auto" onClick={() => setStep(1)}>Fazer meu Raio-X<ArrowRight size={16} /></Button></div></section>;
  if (step > 12) return <XrayResult score={score} result={result} bottleneck={bottleneck} savedAt={savedAt} onEdit={() => setStep(1)} />;
  const question = xrayQuestions[step - 1]; const selected = answers[step - 1]?.optionIndex; const progress = Math.round((step / 12) * 100);
  return <section className="mx-auto max-w-3xl"><div className="mb-5"><div className="mb-3 flex justify-between"><span className="text-xs font-bold uppercase tracking-[.14em] text-gold">Pergunta {step} de 12 · {xrayLabels[question.category]}</span><AutoSaveStatus saving={saving} date={savedAt} /></div><ProgressBar value={progress} /></div><div className="card min-h-[510px] p-6 md:p-9"><h2 className="text-xl font-bold leading-snug text-white">{question.title}</h2><p className="mt-2 text-sm text-muted">{question.subtitle}</p><div className="mt-7 space-y-2">{question.options.map((option, index) => <button className={`option flex gap-4 ${selected === index ? "option-selected" : ""}`} key={option.text} onClick={() => choose(index)}><span className="text-xs font-bold text-gold">0{index + 1}</span><span>{option.text}</span></button>)}</div><div className="mt-8 flex justify-between border-t border-white/8 pt-5"><Button variant="ghost" onClick={() => setStep(step - 1)}><ArrowLeft size={16} />Anterior</Button>{step === 12 ? <Button disabled={selected === undefined} onClick={finish}><Check size={16} />Concluir Raio-X</Button> : <Button disabled={selected === undefined} onClick={() => setStep(step + 1)}>Continuar<ArrowRight size={16} /></Button>}</div></div></section>;
}
function XrayResult({ score, result, bottleneck, savedAt, onEdit }: { score: number; result: ReturnType<typeof getXrayResult>; bottleneck: keyof typeof xrayLabels; savedAt?: string; onEdit: () => void }) {
  return <section className="mx-auto max-w-3xl">
    <VideoLesson title="Raio-X Anti-Curiosos: Como diagnosticar seu funil" />
    <div className="my-6 text-center"><p className="eyebrow">Diagnóstico concluído</p><h2 className="text-2xl font-bold text-white">Seu Raio-X está pronto</h2><div className="mt-3 flex justify-center"><AutoSaveStatus date={savedAt} /></div></div>
    <XrayAnatomy score={`${score} / 36`} classification={result.name} leak={result.level} bottleneck={xrayLabels[bottleneck]} problem={getXrayProblem(score, bottleneck)} />
    <div className="mt-5 flex flex-col gap-3 sm:flex-row"><Button variant="ghost" onClick={onEdit}><Pencil size={16} />Editar respostas</Button><Link className="button button-primary flex-1" href="/central/passo-1-diagnostico">Criar Plano de Correção<ArrowRight size={16} /></Link></div>
  </section>;
}

function XrayAnatomy({ score, classification, leak, bottleneck, problem, illustrative = false }: { score: string; classification: string; leak: string; bottleneck: string; problem: string; illustrative?: boolean }) {
  const metrics = [{ label: "Pontuação", value: score }, { label: "Classificação", value: classification }, { label: "Vazamento", value: leak }, { label: "Gargalo", value: bottleneck }];
  return <div className="card overflow-hidden p-0">{illustrative && <div className="border-b border-white/8 px-5 py-3 text-[10px] font-bold uppercase tracking-[.16em] text-gold">Exemplo ilustrativo</div>}<div className="grid grid-cols-2 border-b border-white/8">{metrics.map((metric) => <div className="border-b border-r border-white/8 p-4 even:border-r-0 [&:nth-last-child(-n+2)]:border-b-0" key={metric.label}><span className="text-[10px] font-bold uppercase tracking-wider text-muted">{metric.label}</span><strong className="mt-2 block text-sm text-white">{metric.value}</strong></div>)}</div><div className="p-5 sm:p-6"><span className="text-[10px] font-bold uppercase tracking-wider text-primary">Problema identificado</span><p className="mt-2 text-sm leading-7 text-[#dbeafe]">{problem}</p></div></div>;
}
